
# generic AWS Codebuild build script for cognify modules.  Produces a zip file of the 'lambda' sub-directory
# For the AWS specification see http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  build:
    commands:
      - echo Building $CODEBUILD_SOURCE_REPO_URL $CODEBUILD_SOURCE_VERSION - initatied by $CODEBUILD_INITIATOR
      - BUILD_DIR="build-output"
      - if [ "$CODEBUILD_SOURCE_VERSION" ]; then BUILD_DIR="build-output-$CODEBUILD_SOURCE_VERSION"; fi
      - echo $BUILD_DIR
      # copy the template file into the lambda directory.
      - cp template.yaml lambda
      # hop into the lambda directory
      - cd lambda
       # determine package name
      - packageName=$( node -pe "require('./package.json').name" )
      # determine version
      - version=$( node -pe "require('./package.json').version" )
      - echo Building $packageName version $version
      # create 'build-output' directory to hold build
      - mkdir $BUILD_DIR
      # copy all files from current (lambda) directory into this new directory
      - cp *.* $BUILD_DIR
      # navigate into this folder
      - cd $BUILD_DIR
      # zip up the contents of the build-output folder, name this file name~version.zip
      - zip -r $packageName~$version.zip ./*
artifacts:
  files:
    # specify build artifacts
    - $BUILD_DIR/$packageName~$version.zip
    - $BUILD_DIR/template.yaml
  base-directory: lambda