AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Set up API Gateway endpoint connected to Lambda function that returns HTML
Resources:
  LambdaWebPageApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: lambda-web-page
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaWebPageLambdaFunction.Arn}/invocations
                  responses: {}
   
  LambdaWebPageLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-web-page
      Handler: index.handler
      Runtime: nodejs10.x
      Description: API Endpoint connected to lambda function, returns HTML.
      MemorySize: 128
      Timeout: 30
      #CodeUri: s3://eftestdemowebpage/lambda-web-page-example~0.1.10.zip
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: 
                Ref: LambdaWebPageApi